config/routes.rb
Rails.application.routes.draw do
  root 'users#top'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post '/users/guest_sign_in', to: 'users#guest_sign_in'
  end
  resources :users
  get 'users/:id/report', to: 'users#report'
  resources :timeposts do
    resources :comments, only: %i[create destroy]
    resources :timelike, only: %i[create destroy]
  end
  resources :methodposts do
    resources :reviews, only: %i[create destroy]
    resources :methodlike, only: %i[create destroy]
  end
  resources :relationships, only: %i[create destroy]
end

app/models/methodpost.rb
class Methodpost < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :method_likes, dependent: :destroy

  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true
  validates :subjects, presence: true
end

app/controllers/methodposts_controller.rb
class MethodpostsController < ApplicationController
  before_action :authenticate_user!, only: %i[show new create edit update destroy]
  def index
    @methodposts = Methodpost.all.order(created_at: :desc)
  end

  def show
    @methodpost = Methodpost.find_by(id: params[:id])
    @methodlikes_count = MethodLike.where(methodpost_id: params[:id]).count
    @reviews = Review.where(methodpost_id: params[:id])
  end

  def new
    @methodpost = Methodpost.new
  end

  def create
    @methodpost = current_user.methodposts.build(methodpost_params)
    if @methodpost.save
      flash[:success] = 'methodpost created!'
      redirect_to methodposts_url
    else
      render 'new'
    end
  end

  def edit
    @methodpost = Methodpost.find_by(id: params[:id])
  end

  def update
    @methodpost = Methodpost.find(params[:id])
    if @methodpost.update(methodpost_params)
      redirect_to methodposts_url
    else
      render 'edit'
    end
  end

  def destroy
    Methodpost.find_by(id: params[:id]).destroy
    flash[:success] = '投稿を削除しました'
    redirect_to methodposts_url
  end

  private

  def methodpost_params
    params.require(:methodpost).permit(:content, :user_id, :subjects)
  end
end

app/helpers/methodposts_helper.rb
module MethodpostsHelper
end

app/views/methodposts/edit.html.erb
<h1>勉強方法の投稿編集ページ</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @methodpost, local: true) do |f| %>
      <p><%= f.label :content %>
      <%= f.text_area :content, class: 'form-control' %></p>

      <p><%= f.label :科目 %> <br />
      <%= f.select :subjects, [["国語","国語"],["現代文", "現代文"], ["古文", "古文"], ["漢文", "漢文"],
                              ["数学","数学"],["数学I・A", "数学I・A"], ["数学II・B", "数学II・B"], ["数学III", "数学III"],
                              ["英語","英語"],["英単語", "英単語"],["英文法", "英文法"],["英文解釈","英文解釈"],["英長文", "英長文"],["リスニング","リスニング"],
                              ["日本史","日本史"],["世界史", "世界史"], ["倫理", "倫理"], ["政治経済", "政治経済"],["地理","地理"],["現代社会","現代社会"],
                              ["物理","物理"],["化学", "化学"], ["生物", "生物"],["地学","地学"],["過去問","過去問"]] %></p>

      <%= f.submit "内容を変更する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/methodposts/index.html.erb
<h1>勉強法投稿一覧</h1>
<p><%= link_to "勉強法投稿新規作成", new_methodpost_path %></p>
<ul>
  <% @methodposts.each do |methodpost| %>
    <li>
    <small>
     <%= time_ago_in_words(methodpost.created_at) %>前
    </small>
    <p><strong>ユーザー名:</strong><%= link_to "#{methodpost.user.name}", "/users/#{methodpost.user_id}" %> ID:<%= methodpost.user_id%></p>
    <p><strong>投稿内容:</strong><%= link_to "#{methodpost.content}", methodpost %>投稿ID:<%= methodpost.id%></p>
    <p><strong>投稿科目:</strong><%= methodpost.subjects%></p>
    <%= render "methodlike/like_button" ,methodpost: methodpost%>
    </li>
    <% @review_count = Review.where(methodpost_id: methodpost.id).count %>
    レビュー（<%= @review_count %>）
  <% end %>

</ul>

app/views/methodposts/new.html.erb
<h1>勉強法投稿ページ</h1>
<div>
  <div>
    <%= form_with(model: @methodpost, local: true) do |f| %>
      <p><%= f.label :content %>
      <%= f.text_area :content, class: 'form-control' %></p>

      <p><%= f.label :科目 %> <br />
      <%= f.select :subjects, [["国語","国語"],["現代文", "現代文"], ["古文", "古文"], ["漢文", "漢文"],
                              ["数学","数学"],["数学I・A", "数学I・A"], ["数学II・B", "数学II・B"], ["数学III", "数学III"],
                              ["英語","英語"],["英単語", "英単語"],["英文法", "英文法"],["英文解釈","英文解釈"],["英長文", "英長文"],["リスニング","リスニング"],
                              ["日本史","日本史"],["世界史", "世界史"], ["倫理", "倫理"], ["政治経済", "政治経済"],["地理","地理"],["現代社会","現代社会"],
                              ["物理","物理"],["化学", "化学"], ["生物", "生物"],["地学","地学"],["過去問","過去問"]] %></p>
 
      <%= f.submit "投稿", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/methodposts/show.html.erb
<h1>勉強法投稿詳細ページ</h1>
<% if current_user %>
<% if @methodpost.user.id ==  current_user.id %>
    <h4><%= link_to "投稿編集", edit_methodpost_path %></h4>
    <h4><%= button_to "投稿削除", "/methodposts/#{@methodpost.id}", method: :delete,data: { confirm: "本当に削除しますか?" } %></h4>
<% end %>
<% end %>
<p><%= @methodpost.content %></p>
<p><%= @methodpost.subjects %></p>
<% if user_signed_in? %>
      <% @methodlikes_count = MethodLike.where(methodpost_id: @methodpost.id).count %>
      <% if @methodlike = MethodLike.find_by(user_id: current_user.id, methodpost_id: @methodpost.id) %>
        <%= button_to  "/methodposts/#{@methodpost.id}/methodlike/#{@methodlike.id}", method: :delete do %>
          <i class="fas fa-heart like-btn-unlike"><%= @methodlikes_count %>いいね</i>
        <% end %>
      <% else %>
          <%= button_to  "/methodposts/#{@methodpost.id}/methodlike", method: :post do %>
            <i class="fas fa-heart like-btn"><%= @methodlikes_count %>いいね</i>
          <% end %>
      <% end %>
<% end %>

<h2>レビューする</h2>
<%= render "reviews/review_form" ,methodpost: @methodpost%>
<h2>レビュー一覧</h2
<%= render "reviews/review_list" %>